/* =====================================================
   card-roles.js — role / targeting classification
   The API returns no type/race fields, so deck-engine.js
   and app.js read this table for role badges, air-coverage
   scoring and cycle average. Keys are the exact API names.

   role   — deck-function label (win-condition and spell are
            load-bearing for scoring; the rest are badges)
   air    — can attack air troops
   splash — damages multiple units at once
   cycle  — elixir cost (used for the cycle-average bonus)
   tags   — archetype tags matched against META_DECKS

   Tower troops have no elixir cost in the API; cycle 0.
   ===================================================== */

var CARD_ROLES = {
  // ── Common ──
  "Knight":          { role: "tank",          air: true,  splash: true,  cycle: 3, tags: ["tank", "splash"] },
  "Archers":         { role: "air-defense",   air: true,  splash: false, cycle: 3, tags: ["air-defense"] },
  "Goblins":         { role: "cycle",         air: true,  splash: false, cycle: 2, tags: ["cycle", "log-bait"] },
  "Minions":         { role: "air-attack",    air: true,  splash: false, cycle: 3, tags: ["air-attack", "cycle"] },
  "Barbarians":      { role: "splash",        air: true,  splash: true,  cycle: 5, tags: ["splash", "air-defense"] },
  "Skeletons":       { role: "cycle",         air: true,  splash: false, cycle: 1, tags: ["cycle", "log-bait"] },
  "Bomber":          { role: "splash",        air: false, splash: true,  cycle: 2, tags: ["splash", "building-target"] },
  "Spear Goblins":   { role: "air-attack",    air: true,  splash: false, cycle: 2, tags: ["air-attack", "cycle", "log-bait"] },
  "Ice Spirit":      { role: "cycle",         air: true,  splash: false, cycle: 1, tags: ["cycle", "control"] },
  "Fire Spirit":     { role: "cycle",         air: true,  splash: false, cycle: 1, tags: ["cycle", "log-bait"] },
  "Goblin Gang":     { role: "swarm",         air: true,  splash: false, cycle: 3, tags: ["log-bait", "cycle"] },
  "Elite Barbarians":{ role: "splash",        air: true,  splash: true,  cycle: 6, tags: ["splash", "push"] },
  "Bats":            { role: "air-attack",    air: true,  splash: false, cycle: 2, tags: ["air-attack", "cycle"] },
  "Royal Recruits":  { role: "building",      air: true,  splash: false, cycle: 7, tags: ["building", "control"] },
  "Skeleton Barrel": { role: "win-condition", air: false, splash: false, cycle: 3, tags: ["win-condition", "building-target", "log-bait"] },
  "Firecracker":     { role: "splash",        air: true,  splash: true,  cycle: 3, tags: ["splash", "air-defense", "cycle"] },
  "Electro Spirit":  { role: "cycle",         air: true,  splash: false, cycle: 1, tags: ["cycle", "control"] },
  "Minion Horde":    { role: "air-attack",    air: true,  splash: true,  cycle: 5, tags: ["air-attack", "splash"] },
  "Zap":             { role: "spell",         air: true,  splash: true,  cycle: 2, tags: ["spell", "control"] },
  "Giant Snowball":  { role: "spell",         air: true,  splash: false, cycle: 2, tags: ["spell", "control"] },
  "Royal Delivery":  { role: "spell",         air: false, splash: true,  cycle: 3, tags: ["spell", "building-target"] },
  "Arrows":          { role: "spell",         air: true,  splash: true,  cycle: 3, tags: ["spell"] },
  "Mortar":          { role: "building",      air: true,  splash: false, cycle: 4, tags: ["building", "control", "air-defense"] },
  "Tesla":           { role: "building",      air: true,  splash: false, cycle: 4, tags: ["building", "air-defense"] },
  "Cannon":          { role: "building",      air: true,  splash: false, cycle: 3, tags: ["building", "air-defense"] },
  "Berserker":       { role: "cycle",         air: true,  splash: false, cycle: 2, tags: ["cycle", "push"] },
  "Royal Giant":     { role: "win-condition", air: false, splash: false, cycle: 6, tags: ["win-condition", "building-target", "siege"] },
  "Rascals":         { role: "support",       air: true,  splash: false, cycle: 5, tags: ["support", "splash"] },
  "Skeleton Dragons":{ role: "air-attack",    air: true,  splash: false, cycle: 4, tags: ["air-attack", "cycle"] },

  // ── Rare ──
  "Giant":           { role: "win-condition", air: false, splash: false, cycle: 5, tags: ["win-condition", "beatdown", "building-target"] },
  "Valkyrie":        { role: "tank",          air: true,  splash: true,  cycle: 4, tags: ["tank", "splash", "air-defense"] },
  "Musketeer":       { role: "air-defense",   air: true,  splash: false, cycle: 4, tags: ["air-defense"] },
  "Wizard":          { role: "splash",        air: true,  splash: true,  cycle: 5, tags: ["splash", "air-defense"] },
  "Mini P.E.K.K.A":  { role: "tank-killer",   air: true,  splash: false, cycle: 4, tags: ["tank-killer", "cycle"] },
  "Hog Rider":       { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "cycle", "building-target", "hog"] },
  "Three Musketeers":{ role: "win-condition", air: true,  splash: false, cycle: 9, tags: ["win-condition", "siege", "splash"] },
  "Ice Golem":       { role: "tank",          air: true,  splash: false, cycle: 2, tags: ["cycle", "tank", "control"] },
  "Mega Minion":     { role: "air-defense",   air: true,  splash: false, cycle: 3, tags: ["air-defense", "cycle"] },
  "Dart Goblin":     { role: "air-defense",   air: true,  splash: false, cycle: 3, tags: ["air-defense", "building-target"] },
  "Zappies":         { role: "air-defense",   air: true,  splash: false, cycle: 4, tags: ["air-defense", "control"] },
  "Flying Machine":  { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "building-target", "siege"] },
  "Elixir Golem":    { role: "win-condition", air: false, splash: false, cycle: 3, tags: ["win-condition", "beatdown", "building-target"] },
  "Battle Healer":   { role: "support",       air: true,  splash: false, cycle: 4, tags: ["support", "air-defense"] },
  "Goblin Demolisher":{ role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "building-target"] },
  "Suspicious Bush": { role: "support",       air: true,  splash: false, cycle: 2, tags: ["cycle", "control"] },
  "Minion Giant":    { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "beatdown", "building-target", "giant"] },
  "Goblin Hut":      { role: "building",      air: true,  splash: false, cycle: 4, tags: ["building", "log-bait", "building-target"] },
  "Inferno Tower":   { role: "building",      air: true,  splash: false, cycle: 5, tags: ["building", "air-defense", "tank-killer"] },
  "Bomb Tower":      { role: "building",      air: true,  splash: true,  cycle: 4, tags: ["building", "splash", "air-defense"] },
  "Barbarian Hut":   { role: "building",      air: true,  splash: true,  cycle: 6, tags: ["building", "splash", "air-defense"] },
  "Tombstone":       { role: "building",      air: true,  splash: false, cycle: 3, tags: ["building", "cycle", "control"] },
  "Furnace":         { role: "building",      air: true,  splash: false, cycle: 4, tags: ["building", "control"] },
  "Goblin Cage":     { role: "building",      air: true,  splash: false, cycle: 4, tags: ["building", "control"] },
  "Fireball":        { role: "spell",         air: true,  splash: true,  cycle: 4, tags: ["spell"] },
  "Rocket":          { role: "spell",         air: true,  splash: false, cycle: 6, tags: ["spell", "building-target"] },
  "Earthquake":      { role: "spell",         air: false, splash: true,  cycle: 3, tags: ["spell", "building-target"] },
  "Heal Spirit":     { role: "spell",         air: true,  splash: false, cycle: 1, tags: ["spell", "cycle"] },
  "Elixir Collector":{ role: "support",       air: false, splash: false, cycle: 6, tags: ["support", "beatdown"] },

  // ── Epic ──
  "P.E.K.K.A":       { role: "tank-killer",   air: false, splash: false, cycle: 7, tags: ["tank-killer"] },
  "Balloon":         { role: "win-condition", air: false, splash: false, cycle: 5, tags: ["win-condition", "beatdown", "building-target", "balloon"] },
  "Witch":           { role: "swarm",         air: false, splash: true,  cycle: 5, tags: ["swarm", "splash"] },
  "Golem":           { role: "win-condition", air: false, splash: false, cycle: 8, tags: ["win-condition", "beatdown", "building-target", "golem"] },
  "Skeleton Army":   { role: "swarm",         air: true,  splash: false, cycle: 3, tags: ["swarm", "tank-killer"] },
  "Baby Dragon":     { role: "splash",        air: true,  splash: true,  cycle: 4, tags: ["splash", "air-attack"] },
  "Prince":          { role: "tank-killer",   air: true,  splash: false, cycle: 5, tags: ["tank-killer", "push"] },
  "Giant Skeleton":  { role: "win-condition", air: true,  splash: false, cycle: 6, tags: ["win-condition", "push"] },
  "Guards":          { role: "support",       air: true,  splash: true,  cycle: 3, tags: ["support", "splash", "control"] },
  "Dark Prince":     { role: "tank-killer",   air: true,  splash: true,  cycle: 4, tags: ["tank-killer", "control"] },
  "Hunter":          { role: "air-defense",   air: true,  splash: true,  cycle: 4, tags: ["air-defense", "splash"] },
  "Executioner":     { role: "splash",        air: true,  splash: true,  cycle: 5, tags: ["splash", "air-defense", "control"] },
  "Bowler":          { role: "splash",        air: true,  splash: true,  cycle: 5, tags: ["splash", "air-defense"] },
  "Lumberjack":      { role: "support",       air: false, splash: false, cycle: 4, tags: ["push", "cycle"] },
  "Battle Ram":      { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "building-target"] },
  "X-Bow":           { role: "win-condition", air: true,  splash: false, cycle: 6, tags: ["win-condition", "siege", "xbow"] },
  "Goblin Drill":    { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "building-target", "log-bait"] },
  "Rage":            { role: "spell",         air: true,  splash: false, cycle: 2, tags: ["spell"] },
  "Goblin Barrel":   { role: "win-condition", air: false, splash: false, cycle: 3, tags: ["win-condition", "log-bait", "building-target"] },
  "Freeze":          { role: "spell",         air: true,  splash: false, cycle: 4, tags: ["spell", "control"] },
  "Mirror":          { role: "spell",         air: true,  splash: false, cycle: 7, tags: ["spell"] },
  "Lightning":       { role: "spell",         air: true,  splash: true,  cycle: 6, tags: ["spell", "control"] },
  "Poison":          { role: "spell",         air: true,  splash: true,  cycle: 4, tags: ["spell"] },
  "Tornado":         { role: "spell",         air: true,  splash: false, cycle: 3, tags: ["spell", "control"] },
  "Clone":           { role: "spell",         air: true,  splash: false, cycle: 3, tags: ["spell"] },
  "Barbarian Barrel":{ role: "spell",         air: false, splash: true,  cycle: 2, tags: ["spell", "log-bait"] },
  "Void":            { role: "spell",         air: true,  splash: false, cycle: 5, tags: ["spell", "control"] },
  "Goblin Curse":    { role: "spell",         air: true,  splash: false, cycle: 2, tags: ["spell", "control"] },
  "Vines":           { role: "spell",         air: true,  splash: false, cycle: 3, tags: ["spell", "control"] },
  "Electro Dragon":  { role: "splash",        air: true,  splash: true,  cycle: 5, tags: ["splash", "air-attack"] },
  "Wall Breakers":   { role: "win-condition", air: false, splash: false, cycle: 2, tags: ["win-condition", "log-bait", "building-target"] },
  "Royal Hogs":      { role: "win-condition", air: false, splash: false, cycle: 5, tags: ["win-condition", "building-target", "hog"] },
  "Goblin Giant":    { role: "win-condition", air: false, splash: false, cycle: 6, tags: ["win-condition", "beatdown", "building-target"] },
  "Cannon Cart":     { role: "support",       air: true,  splash: false, cycle: 5, tags: ["support", "air-defense", "control"] },
  "Rune Giant":      { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "beatdown", "building-target", "giant"] },
  "Electro Giant":   { role: "tank",          air: false, splash: false, cycle: 7, tags: ["tank", "beatdown"] },

  // ── Legendary ──
  "Ice Wizard":      { role: "control",       air: true,  splash: false, cycle: 3, tags: ["control", "air-defense"] },
  "Princess":        { role: "control",       air: true,  splash: false, cycle: 3, tags: ["control", "siege"] },
  "Lava Hound":      { role: "win-condition", air: true,  splash: false, cycle: 7, tags: ["win-condition", "beatdown", "air-only"] },
  "Miner":           { role: "win-condition", air: false, splash: false, cycle: 3, tags: ["win-condition", "control", "building-target"] },
  "Sparky":          { role: "win-condition", air: true,  splash: true,  cycle: 6, tags: ["win-condition", "splash", "beatdown"] },
  "Electro Wizard":  { role: "control",       air: true,  splash: false, cycle: 4, tags: ["control", "air-defense"] },
  "Bandit":          { role: "tank-killer",   air: false, splash: false, cycle: 3, tags: ["tank-killer", "push"] },
  "Night Witch":     { role: "support",       air: false, splash: false, cycle: 4, tags: ["support", "swarm"] },
  "Royal Ghost":     { role: "push",          air: false, splash: true,  cycle: 3, tags: ["push", "splash"] },
  "Ram Rider":       { role: "control",       air: true,  splash: false, cycle: 5, tags: ["control", "air-defense"] },
  "Fisherman":       { role: "control",       air: true,  splash: false, cycle: 3, tags: ["control"] },
  "Magic Archer":    { role: "win-condition", air: true,  splash: false, cycle: 4, tags: ["win-condition", "siege", "building-target", "xbow"] },
  "Mother Witch":    { role: "support",       air: true,  splash: false, cycle: 4, tags: ["support", "swarm"] },
  "Phoenix":         { role: "win-condition", air: true,  splash: false, cycle: 4, tags: ["win-condition", "air-attack"] },
  "Goblin Machine":  { role: "win-condition", air: false, splash: false, cycle: 5, tags: ["win-condition", "building-target"] },
  "Ronin":           { role: "tank-killer",   air: false, splash: false, cycle: 5, tags: ["tank-killer"] },
  "Spirit Empress":  { role: "support",       air: true,  splash: false, cycle: 6, tags: ["support", "cycle"] },
  "The Log":         { role: "spell",         air: false, splash: false, cycle: 2, tags: ["spell", "log-bait"] },
  "Graveyard":       { role: "win-condition", air: true,  splash: false, cycle: 5, tags: ["win-condition", "swarm", "building-target", "graveyard"] },
  "Mega Knight":     { role: "splash",        air: true,  splash: true,  cycle: 7, tags: ["splash", "air-defense", "control"] },
  "Inferno Dragon":  { role: "tank-killer",   air: true,  splash: false, cycle: 4, tags: ["tank-killer", "air-defense"] },

  // ── Champions ──
  "Mighty Miner":    { role: "win-condition", air: false, splash: false, cycle: 4, tags: ["win-condition", "control", "building-target"] },
  "Skeleton King":   { role: "support",       air: false, splash: false, cycle: 4, tags: ["push", "swarm"] },
  "Archer Queen":    { role: "win-condition", air: true,  splash: false, cycle: 5, tags: ["win-condition", "siege"] },
  "Golden Knight":   { role: "win-condition", air: true,  splash: false, cycle: 4, tags: ["win-condition", "push"] },
  "Monk":            { role: "control",       air: true,  splash: false, cycle: 5, tags: ["control"] },
  "Little Prince":   { role: "win-condition", air: true,  splash: false, cycle: 3, tags: ["win-condition", "cycle"] },
  "Goblinstein":     { role: "tank",          air: false, splash: false, cycle: 5, tags: ["tank", "beatdown"] },
  "Boss Bandit":     { role: "tank-killer",   air: false, splash: false, cycle: 6, tags: ["tank-killer", "push"] },

  // ── Tower troops (not counted in the 8-card deck) ──
  "Tower Princess":  { role: "tower",         air: true,  splash: false, cycle: 0, tags: ["tower"] },
  "Cannoneer":       { role: "tower",         air: true,  splash: false, cycle: 0, tags: ["tower"] },
  "Dagger Duchess":  { role: "tower",         air: true,  splash: false, cycle: 0, tags: ["tower"] },
  "Royal Chef":      { role: "tower",         air: true,  splash: false, cycle: 0, tags: ["tower"] },
};
